#!/usr/bin/env bash
#configure domain zone $4=record $5=ip
domain_func()
{
rec=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $4}')
des=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $5}')
echo "The subdomain $2 is a $rec record and points to $des"
}
if [ -z "$2" ]
then
subd=("www" "lb-01" "web-01" "web-02")
for s in "${subd[@]}"
do
domain_func "$1" "$s"
done
else
domain_func "$1" "$2"
fi
