#!/usr/bin/env bash
#configure new server
sudo apt-get -y update 
sudo apt-get -y install nginx
sudo sed -i "\\\tadd_header X-Served-By \$HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
