#!/usr/bin/env bash
#install HAproxy
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
sudo chmod 764 /etc/haproxy/
sudo chmod 764 /etc/haproxy/haproxy.cfg

sudo sed -i "$ a frontend Local_Server \n\t bind *:80 \n\t mode http \n\t default_backend proxy \n\nbackend proxy \n\t mode http \n\t balance roundrobin \n\t server 1238-web-01 34.74.80.43:80 check \n\t server 1238-web-02 54.89.185.132:80 check \n" /etc/haproxy/haproxy.cfg

sudo service haproxy restart
