#!/usr/bin/env bash
#install HAproxy
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get install -y haproxy=2.0.\*

sudo vi /etc/haproxy/haproxy.cfg
#enable HAproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy


frontend  proxy-frontend
        bind *:80
        mode http
        default_backend proxy-backend
backend proxy-backend
        balance roundrobin
        server 294896-web-01 52.73.254.165:80 check
        server 294896-web-02 100.25.23.236:80 check
#back up file
sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
sudo service haproxy restart
