#!/usr/bin/env bash
#install HAproxy
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 294896-web-01 52.73.254.165:80 check\n\tserver 294896-web-02 100.25.23.236:80 check" /etc/haproxy/haproxy.cfg

sudo service haproxy start
