#!/usr/bin/env bash
#solve port 80
sudo apt-get -y update 
sudo apt-get -y install nginx
sudo systemctl start nginx
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart
