#!/usr/bin/env bash
#fizz for 3 buzz for 5
x=1
while [ $x -le 100 ]
do
if [ "$((x % 3))" -eq 0 ]&& [ "$((x % 5))" -eq 0 ]
then
echo "FizzBuzz"
elif [ "$((x % 5))" -eq 0 ]
then
echo "Buzz"
elif [ "$((x % 3))" -eq 0 ]
then
echo "Fizz"
else
echo "$x"
fi
x=$(( x + 1 ))
done
