#!/usr/bin/env bash
#fizz for 3 buzz for 5
x=1
while [ $x -le 100 ]
do
if [ $(expr $x % 3) -eq 0 ]&& [ $(expr $x % 5) -eq 0 ]
then
echo "FizzBuzz"
elif [ $(expr $x % 5) -eq 0 ]
then
echo "Buzz"
elif [ $(expr $x % 3) -eq 0 ]
then
echo "Fizz"
else
echo "$x"
fi
x=$(( x + 1 ))
done
