#!/usr/bin/env bash
#install uncomplicated firewall
sudo apt-get -y update
sudo apt-get -y install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/TCP
sudo ufw allow 443/TCP
sudo ufw allow 80/TCP
sudo ufw enable
